Creating a PR for DC-Portal Initial Template UI
dc-release/dc-portal pull request #5
Opened 2021-06-04 11:26 UTC by paskantishubham

* index.html- Loading react, bootstrap,jquery,etc through cdn.
* src/App.js- Loads UI
* src/Components/Sidebar.js- Created 3 parts of sidebar, 
                    1-Header for GE logo, Title, User Info
                    2-Body for Menu Options
                    3-Footer for copywrite
* src/Components/CenterHeader.js- Used for Search Bar.
* Rest files are just templates which will be used in future.

2021-06-04 14:59 UTC, dkrypt requested changes
1. Please setup a linter for JS. This makes the styling stricter and uniform. A popular choice is `eslint.js`.
2. Please provide a descriptive README for how to get started. For a beginner I want to be able to run the code without hassle. A good documentation is the key to any new project.

2021-06-04 14:59 UTC, dkrypt commented on index.html
> +    <style>
Please maintain a separate CSS file which is referenced from `index.html`

2021-06-07 13:59 UTC, paskantishubham commented
> 1. Please setup a linter for JS. This makes the styling stricter and uniform. A popular choice is `eslint.js`.
> 2. Please provide a descriptive README for how to get started. For a beginner I want to be able to run the code without hassle. A good documentation is the key to any new project.

2021-06-07 14:07 UTC, paskantishubham commented on index.html
> +    <style>
I have made these changes, will be releasing in next PR.

2021-06-07 16:44 UTC, ayasuda-ge commented
@paskantishubham please rename the “assets” to “webui-assets” for backend integration purpose.

2021-06-07 16:45 UTC, ayasuda-ge requested changes
please rename the folder “assets” to “webui-assets” for integration purpose @paskantishubham

2021-06-07 16:48 UTC, ayasuda-ge requested changes
please rename “assets” to “webui-assets” for integration purposes. Please also ensure to leave all artifacts in the webui-assets. @paskantishubham

2021-06-07 17:12 UTC, paskantishubham commented
I have renamed assets folder and did necessary changes to the code as requested by @ayasuda-ge 

@ayasuda-ge Please merge it

2021-06-08 02:14 UTC, ayasuda-ge requested changes
I also notice these folders- “font”, “styling” and index.html are all exposed outside of the “webui-assets” Please help refactor those to be under the “webui-assets” folder. Thanks @paskantishubham

2021-06-08 08:26 UTC, paskantishubham commented
> I also notice these folders- “font”, “styling” and index.html are all exposed outside of the “webui-assets” Please help refactor those to be under the “webui-assets” folder. Thanks @paskantishubham

@ayasuda-ge I have restructured the webui-assets folder, please review it.

2021-06-08 15:15 UTC, ayasuda-ge approved these changes
perfect! Thank you @paskantishubham

2021-06-08 15:16 UTC, merged