Rebase 2.0 with GE GitHub Enterprise mirror
dc-release/dc-portal pull request #76
Opened 2021-09-08 10:35 UTC by dkrypt

This PR introduces latest changes from developers contributing in GE GitHub Enterprise Repository.

2021-09-08 21:16 UTC, ayasuda-ge commented on README.md
> -[dc-portal-1x](https://dc-portal-1x.run.aws-usw02-dev.ice.predix.io/v1.2beta/dcsc) | [swagger](https://dc-portal-1x.run.aws-usw02-dev.ice.predix.io/v1.2beta/assets/swagger-ui/) | [Repo](https://githu
please add back and reconcile.

2021-09-08 21:16 UTC, ayasuda-ge commented on README.md
> -[dc-portal-ext](https://dc-portal-ci-ext.digitalconnect.apps.ge.com/v1.2beta/dc) | [swagger](https://dc-portal-ci-ext.digitalconnect.apps.ge.com/v1.2beta/assets/swagger-ui/) | [Repo](https://github.c
please add back and reconcile.

2021-09-08 21:16 UTC, ayasuda-ge commented on README.md
> -[dc-portal-int](https://dc-portal-ci-int.digitalconnect.apps.ge.com/v1.2beta/dc) | [swagger](https://dc-portal-ci-int.digitalconnect.apps.ge.com/v1.2beta/assets/swagger-ui/) | [Repo](https://github.c
please add back and reconcile.

2021-09-08 21:18 UTC, ayasuda-ge commented on src/middleware/ManageApi.js
> +let Host = "https://dev-threadconnect.apps.ge.com/v1/api";
this must go in the embedded db.

2021-09-08 21:24 UTC, ayasuda-ge commented on src/containers/threadConnect/Users.js
>        userName: "Shubham Paskanti",
this needs to go

2021-09-08 21:24 UTC, ayasuda-ge commented on src/containers/threadConnect/Users.js
>        userId: "503249986",
this needs to be persisted in the db

2021-09-08 21:27 UTC, ayasuda-ge commented on src/containers/threadConnect/APIs.js
> +  const tableData = [
persist in db

2021-09-08 21:34 UTC, ayasuda-ge requested changes
this file breaches the security practice https://github.com/dkrypt/dc-portal/blob/e7429412d58b8cadf959f61a4cfe4aa64164e7d6/src/containers/manage/threadConnect/UpdateManagement.js#L10 @dkrypt @paskantishubham

2021-09-08 21:51 UTC, ayasuda-ge commented on src/containers/threadConnect/IntegrationVersions.js
> +  const tableData = {
This goes in the db.

2021-09-08 22:04 UTC, ayasuda-ge commented
> This PR introduces latest changes from developers contributing in GE GitHub Enterprise Repository.

What are the issues this "latest changes" addressed to? @dkrypt @paskantishubham

2021-09-09 09:59 UTC, paskantishubham commented on src/containers/threadConnect/Users.js
>        userId: "503249986",
@ayasuda-ge This is used just for the mock up. Will move it to APIs once its ready

2021-09-09 09:59 UTC, paskantishubham commented on src/containers/threadConnect/APIs.js
> +  const tableData = [
@ayasuda-ge This is used just for the mock up. Will move it to APIs once its ready

2021-09-09 09:59 UTC, paskantishubham commented on src/containers/threadConnect/IntegrationVersions.js
> +  const tableData = {
@ayasuda-ge This is used just for the mock up. Will move it to APIs once its ready

2021-09-09 15:45 UTC, ayasuda-ge commented on src/middleware/ManageApi.js
> +let Host = "https://dev-threadconnect.apps.ge.com/v1/api";
consider this-
```
data.insert("my-key",{"host":"https://dev-threadconnect.apps.ge.com/v1/api"});

var op = data.get("my-tc-call-info");

- document.Host=op.host;
let ProjectNameListUrl = _`${Host}/tc/project-names`;_


```

2021-09-09 17:43 UTC, dkrypt commented
@ayasuda-ge  I would propose to close this PR, as it does not met the standards of git and also general engineering practices. 
Also, exposes some of the API Endpoints which are unprotected at the moment. This will lead to exposing these endpoints in the history.

I will propose a PR with new standard changes.

2021-09-14 11:28 UTC, closed without merging